version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - rssparser-backend
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8080
    networks:
      - rssparser-backend

networks:
  rssparser-backend: