"""first inicialisation

Revision ID: 33088b1c36cd
Revises:
Create Date: 2022-04-10 18:46:44.188225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33088b1c36cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'measurements',
        sa.Column('uid', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('project', sa.String(), nullable=True),
        sa.Column('date', sa.String(), nullable=True),
        sa.Column('responsible', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('uid')
    )
    op.create_table(
        'trials',
        sa.Column('uid', sa.Integer(), nullable=False, autoincrement=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('status', sa.String(5), nullable=True),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('value', sa.String(), nullable=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('measure_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['measure_id'], ['measurements.uid'], ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('trials')
    # ### end Alembic commands ###

