"""

Revision ID: f7e42dbb3bd6
Revises: 
Create Date: 2022-04-12 17:49:43.579404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e42dbb3bd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('responsible', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('trials',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['measurements.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trials')
    op.drop_table('measurements')
    # ### end Alembic commands ###
